export default {
  getUserData: () => ({
    'id': 6386,
    'name': 'MartinSchmidtMartinSchmidtMar',
    'email': 'schmidtdawid@gmail.com',
    'last_move_date': '2020-11-16 10:26:14',
    'role_id': 10,
    'position_id': 2,
    'team_id': 9,
    'euro': 4294967295,
    'credits': 100,
    'energy': 370913,
    'ban_date': '2000-01-01 00:00:00',
    'register_date': '2020-06-19 10:26:39',
    'avatar': 'https://d2jiusjzwam721.cloudfront.net/avatars-new/pl/L74ot7OfJtYU76M7qdZXAt35hizefGzx.png',
    'ref_id': 0,
    'ip': '85.221.133.127',
    'offensive': 297.25,
    'defensive': 26.85,
    'playmaking': 98.9,
    'condition': 79.6,
    'reading': 20.45,
    'freekicks': 140.32999999999998,
    'pressing': 102.85,
    'efficacy': 21,
    'form': 43,
    'ranking_position': 37,
    'ranking_position_dir': 1,
    'active_set_id': null,
    'facebook_id': '3356376654425174',
    'team_join_date': '2020-07-14 08:20:33',
    'team_cooperation': 7.413,
    'ovr': 98,
    'trained_today': 0,
    'trained_week': 0,
    'packs_today': 0,
    'chat_ban_date': '2020-06-19 10:26:39',
    'partner_id': 6389,
    'fight_id': 0,
    'activated': 1,
    'today_spent_euro': 0,
    'skin_image': '["legendary\\/space-min","platinum\\/ball_destroy-min"]',
    'booster_data': null,
    'face_color': 82,
    'timezone': 'Europe/Warsaw',
    'today_challenge_amount': 0,
    'last_locale': 'PL',
    'skills_without_items': {
      'offensive': 22.25,
      'defensive': 26.85,
      'playmaking': 24.5,
      'reading': 20.45,
      'pressing': 21.25,
      'freekicks': 100.33,
      'condition': 21,
      'efficacy': 21
    },
    'bonus_set': false,
    'active_items': [{
      'id': 9387,
      'user_id': 6386,
      'name': 'Korki Galacticos',
      'type': 'shoes',
      'skill': 'freekicks',
      'bonus': 40,
      'bonus_base': '40.00',
      'special_item': 0,
      'rarity': 'epic',
      'active': true,
      'max_skills': 1000,
      'image': 'krolewski',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 0,
      'enchanted_tier': 0,
      'auction_start_date': null
    }, {
      'id': 9386,
      'user_id': 6386,
      'name': 'Getry Galacticos',
      'type': 'socks',
      'skill': 'pressing',
      'bonus': 40.6,
      'bonus_base': '40.00',
      'special_item': 0,
      'rarity': 'epic',
      'active': true,
      'max_skills': 1000,
      'image': 'krolewski',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 2,
      'enchanted_tier': 0,
      'auction_start_date': null
    }, {
      'id': 9385,
      'user_id': 6386,
      'name': 'Spodenki Galacticos',
      'type': 'trousers',
      'skill': 'pressing',
      'bonus': 41,
      'bonus_base': '40.00',
      'special_item': 0,
      'rarity': 'epic',
      'active': true,
      'max_skills': 1000,
      'image': 'krolewski',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 3,
      'enchanted_tier': 0,
      'auction_start_date': null
    }, {
      'id': 9229,
      'user_id': 6386,
      'name': 'Opaska Mistrza Treningów',
      'type': 'wrist',
      'skill': 'condition',
      'bonus': 58.6,
      'bonus_base': '55.00',
      'special_item': 0,
      'rarity': 'platinum',
      'active': true,
      'max_skills': 1000,
      'image': 'training_wrist',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 6,
      'enchanted_tier': 0,
      'auction_start_date': null
    }, {
      'id': 9230,
      'user_id': 6386,
      'name': 'Piłka Mistrza Typerów',
      'type': 'ball',
      'skill': 'playmaking',
      'bonus': 74.4,
      'bonus_base': '40.00',
      'special_item': 0,
      'rarity': 'legendary',
      'active': true,
      'max_skills': 1000,
      'image': 'tricks_ball',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 18,
      'enchanted_tier': 0,
      'auction_start_date': null
    }, {
      'id': 16622,
      'user_id': 6386,
      'name': 'Test',
      'type': 'shirt',
      'skill': 'offensive',
      'bonus': 275,
      'bonus_base': '110.00',
      'special_item': 0,
      'rarity': 'diamond',
      'active': true,
      'max_skills': 1000,
      'image': 'bvb',
      'auction_price': 0,
      'sellable': 1,
      'locked_date': null,
      'enchant_level': 20,
      'enchanted_tier': 0,
      'auction_start_date': null
    }],
    'position_name': 'Środkowy Napastnik',
    'has_mod_permission': true,
    'role_name': 'Admin',
    'stats_sum': 787.23,
    'level': 98,
    'progress': 40,
    'socket_hash': 'd3ea6fb32a3ee784ede14b067102f53d',
    'unread_messages': 0,
    'is_injured': false,
    'injury_finish': 329,
    'is_banned': false,
    'premium_assistant_expiration': '2020-10-17 08:53:42',
    'job_assistant_expiration': '2020-10-22 14:40:12',
    'training_assistant_expiration': '2020-10-22 14:40:08',
    'tutorial_status': 100,
    'skills_with_items': {
      'offensive': 297.25,
      'defensive': 26.85,
      'playmaking': 98.9,
      'reading': 20.45,
      'pressing': 102.85,
      'freekicks': 140.32999999999998,
      'condition': 79.6,
      'efficacy': 21
    },
    'team': {
      'id': 9,
      'name': 'Arka Gdynia',
      'country': 'ITA',
      'league': 1,
      'owner_id': 6386,
      'assistant_id': 1529,
      'is_team_owner': true,
      'flag': 'it',
      'league_name': '1'
    }
  }),
  isMaximized: jest.fn(),
  getCurrentStep: jest.fn(() => 1),
  getIsAccountBanned: jest.fn(() => false),
  getSocketPrefix: jest.fn(() => 'e77989ed21758e78331b20e477fc5582:'),
};
